name: snaptic
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  fl_chart: 0.68.0
  shimmer: ^3.0.0
  cached_network_image: ^3.0.0
  image_picker: '>=1.1.2'
  intl: 0.20.2
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  share_plus: ^10.0.0
  nfc_manager: ^4.0.0
  supabase_flutter: '>=1.10.0'
  http: ^1.1.0
  url_launcher: ^6.2.1
  webview_flutter: ^4.4.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

assets:
  #- assets/images/logo.png
  
 